arb-dir: lib/l10n/resources
template-arb-file: app_en.arb
output-dir: lib/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [en]
untranslated-messages-file: build/untranslated_messages.json
